name: Lint Task

on:
  workflow_call:

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yarn install & lint
        run: |
          yarn install
          yarn lint
